name: Go CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Tests
      run: make test

    - name: Benchmark
      run: make benchmark

    - name: Build
      run: make build

    - name: Upload build artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./who-pwned-me
